### ISSUE TITLE
蔷薇艾特现在改格式了

### ISSUE THREAD

**Issue by jingming295** [BSTluo/koishi-plugin-adapter-iirose#4]
![image](https://github.com/BSTluo/koishi-plugin-adapter-iirose/assets/48265334/73006c52-93a1-4b6e-9505-ff8709efd681)
现在的艾特是 [*名字*] 而不是  [@名字@]

**Comment by BSTluo** [comment]
？？竟是如此

**Comment by BSTluo** [comment]
等会，以前好像一直是这样的a

**Comment by jingming295** [comment]
原来如此
